### ISSUE TITLE
Does not compile on Mac

### ISSUE THREAD

**Issue by alicerobson** [HEP-FCC/fcc-edm#42]
I am trying to install podio, fcc-edm and fcc-physics on Mac. For each of these I have taken the master from Github and followed the README instructions.

Podio installs fine and tests run as expected.

fcc-edm fails to compile with two items like this.

[ 85%] Building CXX object utilities/CMakeFiles/utilities.dir/DummyGenerator.cc.o
/Users/alice/fccwork0.8/fcc-edm/utilities/DummyGenerator.cc:34:50: error: expected
      '(' for function-style cast or type construction
  writer.registerForWrite<fcc::ParticleCollection>("GenParticle");
                          ~~~~~~~~~~~~~~~~~~~~~~~^

**Comment by jlingema** [comment]
Yes, there was a change in PODIO after we tagged, the discrepancy between PODIO and FCC-EDM is fixed by PR #41. You can use my branch or, better yet, use the tags (v0.6 for PODIO and v0.5 for FCC-EDM)

**Comment by alicerobson** [comment]
Thank you. I used the suggested tags (v0.6 for PODIO and v0.5 for FCC-EDM) and this worked.
