### ISSUE TITLE
sourcing init.sh kills the terminal

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/fcc-edm#43]
Hello, 

With version 0.5, when I do ```source ./init.sh``` on my mac, it just closes the current terminal :-/
This does not happen with https://github.com/cbernet/fcc-edm/tree/working.

@alicerobson did you also get this issue with v0.5? 

Cheers, 

Colin

**Comment by alicerobson** [comment]
It hangs my terminal if I have not run init.sh on the DAG …  but it does at least report the issue. I then had to kill the terminal and start again. 
Alice

**Comment by jlingema** [comment]
(in case there is no mail notification: this is fixed with #44)

**Comment by cbernet** [comment]
Hi Joschka (and Alice)

Thanks for the fix! 
Just one thing, it seems from the mail of Alice that the problem I’ve been experiencing is related to some issue with setting up the dag.
Is that true? Why would podio and fcc-edm depend on that? 
I’m seeing no reference to the dag in the READMEs of podio and fcc-edm. 

Sorry if this is a stupid question (sounds like it)

Cheers! 

Colin

**Comment by jlingema** [comment]
Indeed FCC-EDM now depends on the DAG, since we added a class here that allows to generate a DAG of a particle history, which can be used in fcc-physics and FCCSW. I added the dependency also to the README [here](https://github.com/HEP-FCC/fcc-edm#directed-acyclic-graph).
